#!/bin/bash


function run_me() {
                 geom=$1
                ./itkvis $geom
                 echo "Make description for $geom"
                 echo " ==== 3D model for  $geom ====" > out/${geom}.txt 
                 echo " " >> out/${geom}.txt 
                 echo "used xml files from:" >> out/${geom}.txt 
                 echo "https://svnweb.cern.ch/trac/atlasoff/browser//InnerDetector/InDetTrackingGeometryXML/trunk/share/" >> out/${geom}.txt
                 echo "https://svnweb.cern.ch/trac/atlasoff/browser/InnerDetector/InDetDetDescr/PixelLayouts/BarrelInclinedRef/trunk/data/" >> out/${geom}.txt
                 echo ""  >>  out/${geom}.txt
                 echo "The 3D model is constructed from the following files in $geom:" >> out/${geom}.txt 
                 ls -l ./xml/$geom/*.xml | sed -e"s/ \+/ /g" | cut -d' ' -f 9- >> out/${geom}.txt 
                 echo ""  >> out/${geom}.txt 
                 date -u >> out/${geom}.txt 
                }  



run_me Inclined_Quads
run_me Inclined_Duals
run_me Inclined_Alternative 
